# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-20 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0018_estadocomprobacion_id_periodocontable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadocomprobacion',
            old_name='id_periodoContable',
            new_name='periodoContable_id',
        ),
    ]
