# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-11-21 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contables', '0019_auto_20191019_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocomprobacion',
            name='periodoContable_id',
        ),
    ]
